[main]
network=hoodi

[hoodi]
# Public hoodi test network
http_provider=https://rpc.hoodi.ethpandaops.io
chainid=560048
contract=0x02724c2d1e76Ea3A24247A48F959532cDb152Fb6

[sepolia]
# Public sepolia test network
http_provider=https://ethereum-sepolia-rpc.publicnode.com
chainid=11155111
contract=

[mainnet]
# Production setup should be used ideally via an own node for security
http_provider=
chainid=1
contract=

[anvil]
# for local development
http_provider=http://127.0.0.1:8545
chainid=31337
contract=0x12aedb6639c160b051be89b77717f46eafac282b

