[main]
network=hoodi

[hoodi]
# Public hoodi test network
http_provider=https://rpc.hoodi.ethpandaops.io
chainid=560048
contract=0x25F04B3e59ADb69425a3A4fDA09c5465B69192C5

[sepolia]
# Public sepolia test network
http_provider=https://ethereum-sepolia-rpc.publicnode.com
chainid=11155111
contract=

[mainnet]
# Production setup should be used ideally via an own node for security
http_provider=
chainid=1
contract=

[anvil]
# for local development
http_provider=http://127.0.0.1:8545
chainid=31337
contract=0x12aedb6639c160b051be89b77717f46eafac282b

