#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
#
# build_contract.py - generate the contract artifact for distro_tool.py
#
# Compiles the vyper contract (ape/contracts/distro.vy) and writes a python
# module (src/suse_distro_blockchain/distro_contract.py) holding CONTRACT_ABI
# and CONTRACT_BYTECODE, plus a copy of the contract source next to it as
# package data, so distro_tool.py never ships hand-embedded, possibly stale
# data.
#
# Usage:
#   python3 ape/build_contract.py          (repo root)
#   python3 build_contract.py              (from ape/)
#   python3 ape/build_contract.py --check  (CI: fail if artifact is stale)
#
# Requires vyper (0.4.x, matching ape/ape-config.yaml), either as a python
# module or as the `vyper` CLI.

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(os.path.realpath(__file__)))

DEFAULT_SOURCE = os.path.join(HERE, "contracts", "distro.vy")
DEFAULT_OUTPUT = os.path.join(
    HERE, os.pardir, "src", "suse_distro_blockchain", "distro_contract.py"
)

# Path of the contract source copy inside the installable package, relative to
# the generated artifact. distro_tool.py compares this copy to verify the
# artifact is current, both in the source tree and when installed.
PACKAGE_SOURCE_REL = os.path.join("contracts", "distro.vy")

HEADER = (
    "# SPDX-License-Identifier: GPL-3.0-or-later\n"
    "# AUTO-GENERATED by build_contract.py from the vyper contract source. DO NOT EDIT.\n"
    "# Regenerate after every contract change with:\n"
    "#   python3 ape/build_contract.py   (or: make contract-build)\n"
    "import json\n"
    "\n"
)


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            block = f.read(65536)
            if not block:
                break
            h.update(block)
    return h.hexdigest()


def compile_with_vyper_module(source):
    from vyper import compile_code

    out = compile_code(source, output_formats=["abi", "bytecode"])
    return out["abi"], out["bytecode"]


def compile_with_vyper_cli(source_path):
    try:
        proc = subprocess.run(
            ["vyper", "-f", "abi,bytecode", source_path],
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        sys.exit(
            "vyper is required to build the distro_contract.py artifact.\n"
            "  Install vyper 0.4.x (e.g. pip install vyper==0.4.3) or invoke via\n"
            "  a python that has vyper available, e.g.:\n"
            "    make contract-build PYTHON=/path/to/venv/bin/python"
        )
    if proc.returncode != 0:
        sys.exit(f"vyper CLI failed:\n{proc.stderr}")
    data = json.loads(proc.stdout)
    return data[0], data[1]


def compile_contract(source_path, source_text):
    try:
        return compile_with_vyper_module(source_text)
    except ImportError as e:
        if os.environ.get("VYPER_EXPECT_MISSING") != "1":
            print(f"note: vyper module unavailable ({e}); trying the 'vyper' CLI")
        return compile_with_vyper_cli(source_path)


def render_module(source_rel, source_sha, abi, bytecode):
    abi_json = repr(json.dumps(abi, separators=(",", ":")))
    body = (
        f'CONTRACT_SOURCE = "{source_rel}"\n'
        f'CONTRACT_SHA256 = "{source_sha}"\n'
        f"CONTRACT_ABI = json.loads({abi_json})\n"
        f'CONTRACT_BYTECODE = "{bytecode}"\n'
    )
    return "".join((HEADER, body))


def read_artifact(path):
    module = {}
    code = compile(open(path).read(), str(path), "exec")
    ctx = {"json": json, "CONTRACT_ABI": None, "CONTRACT_BYTECODE": None}
    exec(code, ctx)
    module["CONTRACT_SOURCE"] = ctx.get("CONTRACT_SOURCE")
    module["CONTRACT_SHA256"] = ctx.get("CONTRACT_SHA256")
    module["CONTRACT_ABI"] = ctx.get("CONTRACT_ABI")
    module["CONTRACT_BYTECODE"] = ctx.get("CONTRACT_BYTECODE")
    return module


def _artifact_current(output_abs, source_sha):
    """True when the artifact and packaged source copy match the source."""
    if not os.path.exists(output_abs):
        return False
    try:
        artifact = read_artifact(output_abs)
    except Exception:
        return False
    if artifact.get("CONTRACT_SHA256") != source_sha:
        return False
    pkg_source = os.path.join(os.path.dirname(output_abs), PACKAGE_SOURCE_REL)
    return os.path.exists(pkg_source) and sha256_file(pkg_source) == source_sha


def main():
    ap = argparse.ArgumentParser(
        prog="build_contract.py",
        description="Generate the distro_contract.py artifact for distro_tool.py "
        "from the vyper contract source.",
    )
    ap.add_argument("-o", "--output", default=DEFAULT_OUTPUT, help="output module path")
    ap.add_argument("--source", default=DEFAULT_SOURCE, help="vyper contract source path")
    ap.add_argument("--check", action="store_true", help="only verify the artifact is current")
    ap.add_argument("--quiet", action="store_true", help="print nothing on success")
    args = ap.parse_args()

    source_abs = os.path.abspath(args.source)
    output_abs = os.path.abspath(args.output)
    if not os.path.exists(source_abs):
        sys.exit(f"Contract source not found: {source_abs}")
    source_sha = sha256_file(source_abs)

    if not args.check and _artifact_current(output_abs, source_sha):
        # Nothing changed: no vyper invocation needed. This keeps the target
        # safe to run in build environments without a working vyper.
        if not args.quiet:
            print(f"OK: {output_abs} is up to date, nothing to do")
        return 0

    if args.check:
        if not os.path.exists(output_abs):
            sys.exit(f"Artifact missing: {output_abs} (run: python3 ape/build_contract.py)")
        artifact = read_artifact(output_abs)
        if artifact.get("CONTRACT_SHA256") != source_sha:
            sys.exit(
                f"Artifact {output_abs} is stale: contract source changed since it was built.\n"
                "  Rebuild: python3 ape/build_contract.py   (or: make contract-build)"
            )
        pkg_source_abs = os.path.join(os.path.dirname(output_abs), PACKAGE_SOURCE_REL)
        if not os.path.exists(pkg_source_abs) or sha256_file(pkg_source_abs) != source_sha:
            sys.exit(
                f"Packaged source copy {pkg_source_abs} is missing or stale.\n"
                "  Rebuild: python3 ape/build_contract.py   (or: make contract-build)"
            )
        if not args.quiet:
            print(f"OK: {output_abs} is up to date")
        return 0

    with open(source_abs) as f:
        source_text = f.read()
    abi, bytecode = compile_contract(source_abs, source_text)
    out_dir = os.path.dirname(output_abs)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    pkg_source_abs = os.path.join(out_dir, PACKAGE_SOURCE_REL)
    os.makedirs(os.path.dirname(pkg_source_abs), exist_ok=True)
    shutil.copyfile(source_abs, pkg_source_abs)
    with open(output_abs, "w") as f:
        f.write(render_module(PACKAGE_SOURCE_REL, source_sha, abi, bytecode))
    if not args.quiet:
        print(f"Wrote {output_abs}")
        print(f"  source  : {source_abs} ({source_sha[:12]}…)")
        print(f"  copy    : {pkg_source_abs}")
        print(f"  abi     : {len(abi)} entries")
        print(f"  bytecode: {(len(bytecode) - 2) // 2} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())